export const siteConfig = {
  name: "PixelForge AI",
  description: "Free AI-powered image tools — remove backgrounds, upscale, compress, and convert images instantly in your browser.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://pixelforge.ai",
  ogImage: "/og-image.png",
};

export const tools = [
  {
    id: "remove-bg",
    name: "Remove Background",
    description: "Remove image backgrounds instantly with AI. Get clean, transparent PNGs in seconds.",
    icon: "Eraser",
    href: "/tools/remove-bg",
    badge: "AI",
    popular: true,
    metaTitle: "Free AI Background Remover — Remove Image Backgrounds Online",
    metaDescription: "Remove backgrounds from images instantly with AI. Free, no signup required. Download transparent PNG in seconds.",
    keywords: ["remove background", "background remover", "AI background removal", "transparent background", "remove bg"],
  },
  {
    id: "upscale",
    name: "AI Upscale",
    description: "Enhance and upscale images up to 4x with AI. Fix blurry and low-resolution photos.",
    icon: "Maximize",
    href: "/tools/upscale",
    badge: "AI",
    popular: true,
    metaTitle: "Free AI Image Upscaler — Enhance & Enlarge Photos Online",
    metaDescription: "Upscale images up to 4x with AI. Fix blurry, pixelated, and low-resolution photos. Free to try, no signup.",
    keywords: ["image upscaler", "AI upscale", "enhance image", "increase resolution", "upscale photo"],
  },
  {
    id: "compress",
    name: "Compress Image",
    description: "Reduce image file size by up to 90% without losing quality. Fast and private.",
    icon: "FileDown",
    href: "/tools/compress",
    badge: "Free",
    popular: true,
    metaTitle: "Free Image Compressor — Reduce Image Size Without Quality Loss",
    metaDescription: "Compress images by up to 90% without visible quality loss. Free, fast, and private. No upload limits.",
    keywords: ["image compressor", "compress image", "reduce image size", "optimize image", "shrink image"],
  },
  {
    id: "convert",
    name: "Convert Format",
    description: "Convert images between PNG, JPEG, WebP, AVIF, and more. Batch conversion supported.",
    icon: "RefreshCw",
    href: "/tools/convert",
    badge: "Free",
    popular: false,
    metaTitle: "Free Image Format Converter — PNG, JPG, WebP, AVIF Converter",
    metaDescription: "Convert images between PNG, JPEG, WebP, AVIF and more formats instantly. Free, no signup required.",
    keywords: ["image converter", "png to jpg", "webp converter", "format converter", "image format"],
  },
  {
    id: "enhance",
    name: "AI Enhance",
    description: "Restore and enhance old, blurry, or damaged photos with AI-powered face restoration.",
    icon: "Sparkles",
    href: "/tools/enhance",
    badge: "AI",
    popular: false,
    metaTitle: "AI Photo Enhancer — Fix Blurry & Old Photos Online",
    metaDescription: "Enhance and restore old, blurry, or damaged photos with AI. Fix faces, sharpen details, and improve quality.",
    keywords: ["photo enhancer", "AI enhance", "fix blurry photo", "restore old photo", "photo restoration"],
  },
  {
    id: "resize",
    name: "Resize Image",
    description: "Resize images to any dimension. Maintain aspect ratio or crop to exact sizes.",
    icon: "Move",
    href: "/tools/resize",
    badge: "Free",
    popular: false,
    metaTitle: "Free Image Resizer — Resize Photos to Any Size Online",
    metaDescription: "Resize images to any dimension instantly. Maintain aspect ratio, crop, or set exact pixel sizes. Free.",
    keywords: ["image resizer", "resize image", "resize photo", "image dimensions", "crop image"],
  },
] as const;

export type Tool = (typeof tools)[number];
